version: '3'

services:
  db:
    image: postgres:15rc1-alpine3.16
    container_name: zebra_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

  zebra_app:
    image: vial0ft/zebra-code:latest
    container_name: zebra_app
    restart: always
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - PORT=8000
    ports:
      - '8500:8000'
    networks:
      - backend
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  backend: {}
